# Generated by Django 3.2.9 on 2021-11-23 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dia', models.TextField(blank=True, null=True)),
                ('mes', models.TextField(blank=True, null=True)),
                ('anio', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='static')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('dni', models.TextField(blank=True, null=True)),
                ('carrera', models.TextField(blank=True, null=True)),
                ('horas', models.TextField(blank=True, null=True)),
                ('firmaNameI', models.TextField(blank=True, null=True)),
                ('firmaPuestoI', models.TextField(blank=True, null=True)),
                ('firmaNameD', models.TextField(blank=True, null=True)),
                ('firmaPuestoD', models.TextField(blank=True, null=True)),
                ('sede', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
