# Generated by Django 3.2.7 on 2021-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.TextField(blank=True, null=True)),
                ('mes', models.TextField(blank=True, null=True)),
                ('anio', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('apellido', models.TextField(blank=True, null=True)),
                ('dni', models.TextField(blank=True, null=True)),
                ('carrera', models.TextField(blank=True, null=True)),
                ('horas', models.TextField(blank=True, null=True)),
                ('firmaNameI', models.TextField(blank=True, null=True)),
                ('firmaPuestoI', models.TextField(blank=True, null=True)),
                ('firmaNameD', models.TextField(blank=True, null=True)),
                ('firmaPuestoD', models.TextField(blank=True, null=True)),
                ('sede', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
