# Generated by Django 3.2.7 on 2021-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_datafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='firmaNameD',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='firmaNameI',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='firmaPuestoD',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='firmaPuestoI',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='upload',
            name='sede',
            field=models.CharField(blank=True, choices=[('Carhue', 'Carhue'), ('Trenque Lauquen', 'Trenque Lauquen'), ('Olavarría', 'Olavarría'), ('General Roca', 'General Roca'), ('G. Pico', 'G. Pico'), ('Mar del Plata', 'Mar del Plata'), ('Daireaux', 'Daireaux'), ('Coronel Suarez', 'Coronel Suarez'), ('Pehuajo', 'Pehuajo'), ('Tres Lomas', 'Tres Lomas'), ('Villa Regina', 'Villa Regina')], default='Carhue', max_length=50, null=True),
        ),
    ]
